SBIT-379: fix redirection in BannerRedirect component
bitlogic/bitlogic.io pull request #284
Opened 2024-09-04 15:38 UTC by GonzalezMaxi

2024-09-05 11:59 UTC, marino-martin requested changes

2024-09-05 11:59 UTC, marino-martin commented on src/components/BannerRedirect/BannerRedirect.js
> +        <button tabIndex={-1} className="BannerRedirect__wrapper__btn">
usar solamente el boton con el evento onclick en lugar del anchor adentro del boton

2024-09-05 12:32 UTC, GonzalezMaxi commented on src/components/BannerRedirect/BannerRedirect.js
> +        <button tabIndex={-1} className="BannerRedirect__wrapper__btn">
Se realizaron los cambios requeridos con el siguiente commit "SBIT-379: fix BannerRedirect component"

2024-09-05 12:34 UTC, marino-martin requested changes

2024-09-05 12:34 UTC, marino-martin commented on src/components/BannerRedirect/BannerRedirect.js
> +    event.preventDefault()
no seria necesario el preventDefault

2024-09-10 12:19 UTC, GonzalezMaxi commented on src/components/BannerRedirect/BannerRedirect.js
> +    event.preventDefault()
Se realizó el cambio requerido en el siguiente commit: "SBIT-379: remove event.preventDefault"

2024-09-10 12:21 UTC, marino-martin approved these changes

2024-09-10 12:21 UTC, merged